services:
  - type: web
    name: mistersoftee-truck-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    healthCheckPath: /health
    envVars:
      - key: GEOTAB_USERNAME
        sync: false
      - key: GEOTAB_PASSWORD
        sync: false
      - key: GEOTAB_DATABASE
        sync: false
      - key: GEOTAB_SERVER
        sync: false
